New aggregations #265
enonic/doc-xp pull request #280
Opened 2021-05-17 13:07 UTC by anatol-sialitski

2021-05-18 06:40 UTC, rymsha requested changes

2021-05-18 06:40 UTC, rymsha commented on docs/storage/aggregations.adoc
> +image:xp-770.svg[XP 7.7.0,opts=inline] minDocCount (int):: Only include bucket in result if number of hits <= ``minDocCount``. This parameter is optional.
```suggestion
image:xp-770.svg[XP 7.7.0,opts=inline] minDocCount (int):: Only include bucket in result if number of hits is ``minDocCount`` or more. This parameter is optional.
```

2021-05-18 10:42 UTC, anatol-sialitski commented on docs/storage/aggregations.adoc
> +image:xp-770.svg[XP 7.7.0,opts=inline] minDocCount (int):: Only include bucket in result if number of hits <= ``minDocCount``. This parameter is optional.
Thank you. Done

2021-05-19 11:11 UTC, alansemenov approved these changes

2021-05-19 11:11 UTC, merged