Scheduler #269
enonic/doc-xp pull request #296
Opened 2021-05-21 13:15 UTC by vbradnitski

2021-05-22 08:41 UTC, rymsha requested changes

2021-05-22 08:41 UTC, rymsha commented on docs/api/lib-scheduler.adoc
> +== Events
What?

2021-05-22 08:41 UTC, rymsha commented on docs/api/lib-scheduler.adoc
> +.Obtains details for an active task:
```suggestion
.Obtains details of a scheduled job:
```

2021-05-22 08:41 UTC, rymsha commented on docs/api/lib-scheduler.adoc
> +On clustered environments aggregated list is returned.
Why is it relevant?

2021-05-24 07:27 UTC, vbradnitski commented on docs/api/lib-scheduler.adoc
> +== Events
copied from somewhere

2021-05-24 07:28 UTC, vbradnitski commented on docs/api/lib-scheduler.adoc
> +== Events
we have it in a bunch of libs actually

2021-05-25 11:14 UTC, rymsha commented on docs/framework/scheduler.adoc
> +NOTE: Several jobs can describe the same task descriptor, so the same code can be run by different threads simultaneously. Also, if the execution time of the task is longer than the cron period (espe
```suggestion
NOTE: Several jobs can describe the same task descriptor, so the same code can be run by different threads simultaneously. Also, if the execution time of the task is longer than the cron period (especially important for long-term jobs) then a new task can be started before the previous is finished.
```

2021-05-25 11:14 UTC, rymsha approved these changes

2021-05-26 12:46 UTC, alansemenov requested changes

2021-05-26 12:46 UTC, alansemenov commented on docs/framework/scheduler.adoc
> +Asynchronous background named <<tasks#, tasks>> can be scheduled by XP platform both for cluster and one-node environment.
"_Asynchronous background_" what?

2021-05-26 12:46 UTC, alansemenov commented on docs/framework/scheduler.adoc
> +It guara.
Is it latin? :)

2021-05-26 12:46 UTC, alansemenov commented on docs/deployment/config.adoc
> +Properties started with `init-job.my-job1` describe properties of `my-job1` job.
"_Properties prefixed with..._" or "_Properties init-job.my-job1.*_"

2021-05-26 12:46 UTC, alansemenov commented on docs/deployment/config.adoc
> +Properties started with `init-job.my-job2` describe properties of `my-job2` job.
Same here

2021-05-26 12:46 UTC, alansemenov commented on docs/deployment/config.adoc
> +Configure default custom jobs to be created for scheduling at instance start. Skip creation if a job with the same name exists already. Only recurring (cron) jobs can be created by the config file. T
"_when an XP instance starts_"

2021-05-26 12:46 UTC, alansemenov commented on docs/deployment/config.adoc
> +Properties started with `init-job.<my-job-name>` will describe properties of a job with `<my-job-name>` name.
"_Properties prefixed with..._" or "_Properties init-job.<my-job-name>.*_"

2021-05-26 12:46 UTC, alansemenov commented on docs/deployment/config.adoc
> +|`true` - a created job will be able to be run according to its cron value and timezone. `false` - the job will be created, but never run until it changes.
Until what changes? the property value? the job?

2021-05-26 12:46 UTC, alansemenov commented on docs/api/lib-scheduler.adoc
> +Add the following into your `build.gradle` file:
"_...to your..._"

2021-05-26 12:46 UTC, alansemenov commented on docs/api/lib-scheduler.adoc
> +Creates a job to be scheduled and run in the background.
Just "_Creates a scheduled job_", otherwise it looks like if the job will run immediately. Or "_Create and schedule a job_"

2021-05-26 12:48 UTC, alansemenov commented on docs/deployment/config.adoc
> +|`true` - a created job will be able to be run according to its cron value and timezone. `false` - the job will be created, but never run until it changes.
Should probably be "_the job will be created, but never run until this property is set to `true`_"

2021-05-27 07:53 UTC, vbradnitski commented on docs/framework/scheduler.adoc
> +Asynchronous background named <<tasks#, tasks>> can be scheduled by XP platform both for cluster and one-node environment.
"Asynchronous background named tasks"

2021-05-27 08:35 UTC, alansemenov approved these changes

2021-05-27 08:35 UTC, merged