New Scheduled Jobs and Management endpoints #271
enonic/doc-xp pull request #301
Opened 2021-05-27 09:26 UTC by vbradnitski

2021-05-27 09:29 UTC, rymsha requested changes

2021-05-27 09:29 UTC, rymsha commented on docs/runtime/management.adoc
> +WARNING: Make sure you have a backup of the installation available before running a cleanUp.
```suggestion
WARNING: Make sure you have a backup of the installation available before running a cleanup.
```

2021-05-27 09:29 UTC, rymsha commented on docs/runtime/management.adoc
> + POST system/cleanUpAuditLog
I think, url is different

2021-05-28 10:54 UTC, alansemenov requested changes
Can we have some examples that showcase usage of `ageThreshold`? Like an example to run the job every Sunday, an example to run it on the 1st of every month etc.

2021-05-31 09:16 UTC, alansemenov approved these changes

2021-05-31 09:16 UTC, merged