Documentation for Query DSL #365
enonic/doc-xp pull request #366
Opened 2021-12-10 13:18 UTC by vbradnitski

2022-02-01 10:17 UTC, rymsha requested changes
I think JS API need to be slightly updated, too

2022-02-01 10:17 UTC, rymsha commented on docs/storage/dsl.adoc
> +      "_name^3",
I don't see ^ documented anywhere

2022-02-01 10:17 UTC, rymsha commented on docs/storage/dsl.adoc
> +During ngram indexing, the term "foxy" is also indexed as: "f", "fo", and "fox".
This is actually called "edge n-gram".

2022-02-02 15:46 UTC, rymsha requested changes

2022-02-02 15:46 UTC, rymsha commented on docs/storage/dsl.adoc
> +      "2015-02-26T12:00:00-02:23"
```suggestion
      "2015-02-26T12:00:00-02:23:00Z"
```

2022-02-02 15:46 UTC, rymsha commented on docs/storage/dsl.adoc
> +      "2015-02-26T12:00:00-02:23"
```suggestion
      "2015-02-26T12:00:00-02:23:00Z"
```

2022-02-02 15:46 UTC, rymsha commented on docs/storage/dsl.adoc
> +NOTE: You can boost - thus increasing or decreasing hit-score pr field basis. By providing more than one field to the query by appending a weight-factor: ^N
```suggestion
NOTE: You can boost - thus increasing or decreasing hit-score per field basis. By providing more than one field to the query by appending a weight-factor: ^N
```

2022-02-02 15:46 UTC, rymsha commented on docs/storage/dsl.adoc
> +
`time` is missing

2022-02-03 12:29 UTC, rymsha approved these changes

2022-02-14 09:25 UTC, alansemenov requested changes

2022-02-14 09:26 UTC, alansemenov commented
I've changed a few *Example requests:*, but they should be replaced everywhere in the document. It should be either "_Sample requests_" or "_Request examples_".

2022-02-23 12:12 UTC, alansemenov approved these changes

2022-02-23 12:12 UTC, merged