Document default CSP #371
enonic/doc-xp pull request #374
Opened 2022-01-11 08:52 UTC by rymsha

2022-01-11 13:48 UTC, sigdestad commented
A bit unclear this one: "page.defaultContentSecurityPolicy" - Does it apply to site engine, webapps, admin - or all? If this header only applies to site engine, I think it should be called "site.default.." And explicitly state it only relates to site engine.

What about admin, shouldn't there be a default security policy for admin apps as well?

2022-01-11 13:49 UTC, sigdestad commented
Also, how does this relate to the "default headers" config that can be set for the web config?

2022-01-11 13:56 UTC, alansemenov commented
> A bit unclear this one: "page.defaultContentSecurityPolicy" - Does it apply to site engine, webapps, admin - or all? If this header only applies to site engine, I think it should be called "site.default.." And explicitly state it only relates to site engine.

If we're going to ditch "`site`" in favour of "`cms`", maybe it should be called "`cms.defaultContentSecurityPolicy`"

> What about admin, shouldn't there be a default security policy for admin apps as well?

Yes, but this config won't have effect on them, CSP will always be enforced in the admin apps.

2022-01-11 14:08 UTC, rymsha commented
> Also, how does this relate to the "default headers" config that can be set for the web config?

It is not related to default headers at all.

> A bit unclear this one: "page.defaultContentSecurityPolicy" - Does it apply to site engine, webapps, admin - or all? If this header only applies to site engine, I think it should be called "site.default.." And explicitly state it only relates to site engine.

it is complicated...
There are two endpoints `/site` and `/admin/site`. 
`/site` endpoint is not affected at all by this configuration. Calling it `site.defaultContentSecurityPolicy` would be confusing.
`/admin/site` - is affected. 
They both relay the work to `PageHandler` - which is the "real" engine. That is why it is called `page.`

None of `/_/` endpoints (components, webapps, services) are affected by this config.

2022-01-14 13:59 UTC, alansemenov requested changes

2022-01-14 13:59 UTC, alansemenov commented on docs/release/upgrade.adoc
> +It is possible to turn the header off or configure via `page.defaultContentSecurityPolicy` value.
It is possible to configure the header via `page.defaultContentSecurityPolicy` value or go back to previous behaviour by setting `page.defaultContentSecurityPolicy` to an empty value.

2022-01-14 14:11 UTC, rymsha commented on docs/release/upgrade.adoc
> +It is possible to turn the header off or configure via `page.defaultContentSecurityPolicy` value.
```suggestion
It is possible to configure the header via `page.defaultContentSecurityPolicy` value or go back to previous behavior by setting `page.defaultContentSecurityPolicy` to an empty value.
```

2022-01-14 15:47 UTC, alansemenov approved these changes

2022-01-14 15:47 UTC, merged