Document the system audit-log #209
enonic/doc-xp pull request #385
Opened 2022-03-30 11:07 UTC by anatol-sialitski

2022-03-30 11:10 UTC, rymsha approved these changes

2022-03-31 11:38 UTC, alansemenov requested changes

2022-03-31 11:38 UTC, alansemenov commented on docs/auditLogs.adoc
> +XP registers only successfully completed actions in the `system.auditlog` repository for `content`, `applications`, `principals` and `ID providers`.
```suggestion
XP registers successfully completed actions that affect content, applications, principals and ID providers in the `system.auditlog` repository.
```

2022-03-31 11:38 UTC, alansemenov commented on docs/auditLogs.adoc
> +Below you can see the examples how data stores for actions with the following types:
```suggestion
Below you can see some examples of how data is stored for various actions:
```

2022-03-31 11:38 UTC, alansemenov commented on docs/auditLogs.adoc
> +In order to enable or disable audit logs for `ID providers` and principals entities such as `users`, `roles` and `groups` you have to reference to the `com.enonic.xp.security.cfg` configuration file
```suggestion
In order to enable or disable audit logs for actions affecting ID providers and principal entities (such as `users`, `roles` and `groups`) you have to modify configuration file `com.enonic.xp.security.cfg` and set `auditlog.enabled` option to `true` to enable or `false` to disable logging. Default value is `true`.
```

2022-03-31 11:38 UTC, alansemenov commented on docs/auditLogs.adoc
> +In order to enable or disable audit logs for `Applications` you have to reference to the `com.enonic.xp.app.cfg` configuration file and set value as `true` to enable and as `false` to disable for the
```suggestion
In order to enable or disable audit logs for application actions you have to modify configuration file `com.enonic.xp.app.cfg` and set `auditlog.enabled` option to `true` to enable or `false` to disable logging. Default value is `true`.
```

2022-03-31 11:38 UTC, alansemenov commented on docs/auditLogs.adoc
> +In order to enable or disable audit logs for `Content` you have to reference to the `com.enonic.xp.content.cfg` configuration file and set value as `true` to enable and as `false` to disable for the
```suggestion
In order to enable or disable audit logs for content actions you have to modify configuration file `com.enonic.xp.content.cfg` and set `auditlog.enabled` option to `true` to enable or `false` to disable logging. Default value is `true`.
```

2022-03-31 14:30 UTC, anatol-sialitski commented on docs/auditLogs.adoc
> +In order to enable or disable audit logs for `ID providers` and principals entities such as `users`, `roles` and `groups` you have to reference to the `com.enonic.xp.security.cfg` configuration file
done

2022-03-31 14:30 UTC, anatol-sialitski commented on docs/auditLogs.adoc
> +In order to enable or disable audit logs for `Applications` you have to reference to the `com.enonic.xp.app.cfg` configuration file and set value as `true` to enable and as `false` to disable for the
done

2022-03-31 14:30 UTC, anatol-sialitski commented on docs/auditLogs.adoc
> +In order to enable or disable audit logs for `Content` you have to reference to the `com.enonic.xp.content.cfg` configuration file and set value as `true` to enable and as `false` to disable for the
done

2022-03-31 14:30 UTC, anatol-sialitski commented on docs/auditLogs.adoc
> +Below you can see the examples how data stores for actions with the following types:
done

2022-03-31 14:43 UTC, alansemenov approved these changes

2022-03-31 14:43 UTC, merged