lib-app and lib-schema docs #413
enonic/doc-xp pull request #414
Opened 2022-08-13 14:33 UTC by vbradnitski

2022-08-15 14:28 UTC, rymsha commented on docs/api/lib-app.adoc
> +Checks if there is virtual application with the specified key.
```suggestion
Checks if there is a virtual application with the specified key.
```

2022-08-21 11:50 UTC, alansemenov requested changes

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +Returns installed application. If both local and virtual apps are installed with specified key, then local will be in the result.
```suggestion
Returns an installed application. If a local and a virtual app are both installed with the specified key, then the local one will take precedence and will be returned in the result.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +*object* : (<<#Application,`Application`>>) Detail information for the application. Or null if the application could not be found.
Properties object of an installed application with the specified key, or `null` if the application could not be found.

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +Fetches all installed applications. If both local and virtual apps are installed with the same key, then local will be in the result.
Fetches all installed applications. If a local and a virtual app are both installed with the same key, then the local one will take precedence and will be returned in the result.

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +Returns the descriptor of the installed application.
```suggestion
Returns descriptor of an installed application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +Creates a virtual application with the specified key together with schema repositories nodes inside it.
```suggestion
Creates a virtual application with the specified key together with schema repositories nodes inside of it.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +*object* : (<<#Application,`Application`>>) Information for the created application.
```suggestion
*object* : (<<#Application,`Application`>>) Properties object of the created application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +*boolean* : `true` if succeed and `false` otherwise.
```suggestion
*boolean* : `true` if the operation succeeded, otherwise `false`.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +*boolean* : `true` if the virtual application exists and `false` otherwise.
```suggestion
*boolean* : `true` if a virtual application with the specified key exists, otherwise `false`.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +Checks if there is local installed application with the specified key.
```suggestion
Checks if there is a local installed application with the specified key.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-app.adoc
> +*boolean* : `true` if the real application exists and `false` otherwise.
```suggestion
*boolean* : `true` if the local application exists, otherwise `false`.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Fetches schema from an application.
```suggestion
Fetches a schema from an application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#schema,`Schema`>>) Detail information for the fetched schema.
```suggestion
*object* : (<<#schema,`Schema`>>) Properties object of the fetched schema.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Creates dynamic schema in virtual application.
```suggestion
Creates a dynamic schema in a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#schema,`Schema`>>) Detail information for the created dynamic schema.
```suggestion
*object* : (<<#schema,`Schema`>>) Properties object of the created schema.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Updates dynamic schema in virtual application.
```suggestion
Updates a dynamic schema in a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#schema,`Schema`>>) Detail information for the modified dynamic schema.
```suggestion
*object* : (<<#schema,`Schema`>>) Properties object of the modified schema.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Removes dynamic schema from virtual application.
```suggestion
Removes a dynamic schema from a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +.Updates a mixin schema:
```suggestion
.Deletes a mixin schema:
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Fetches component from an application.
```suggestion
Fetches a component from an application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#component,`Component`>>) Detail information for the fetched component.
```suggestion
*object* : (<<#component,`Component`>>) Properties object of the fetched component.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Creates dynamic component in virtual application.
```suggestion
Creates a dynamic component in a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#component,`Component`>>) Detail information for the created dynamic component.
```suggestion
*object* : (<<#component,`Component`>>) Properties object of the created dynamic component.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Updates dynamic component in virtual application.
```suggestion
Updates a dynamic component in a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#component,`Component`>>) Detail information for the modified dynamic component.
```suggestion
*object* : (<<#component,`Component`>>) Properties object of the modified dynamic component.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Removes dynamic component from virtual application.
```suggestion
Removes a dynamic component from a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#styles,`Styles`>>) Detail information for the fetched styles.
```suggestion
*object* : (<<#styles,`Styles`>>) Properties object with the fetched styles.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Create styles in virtual application.
```suggestion
Create styles in a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Updates dynamic styles in virtual application.
```suggestion
Updates dynamic styles in a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#styles,`Styles`>>) Detail information for the modified styles.
```suggestion
*object* : (<<#styles,`Styles`>>) Properties object with the modified styles.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Removes dynamic styles from virtual application.
```suggestion
Removes dynamic styles from a virtual application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Fetch site descriptor from an application.
```suggestion
Fetch a site descriptor from an application.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +*object* : (<<#site,`Site`>>) Detail information for fetched site descriptor.
```suggestion
*object* : (<<#site,`Site`>>) Properties object of the fetched site descriptor.
```

2022-08-21 11:50 UTC, alansemenov commented on docs/api/lib-schema.adoc
> +Updates dynamic site descriptor in virtual application.
```suggestion
Updates dynamic site descriptor in a virtual application.
```

2022-08-22 18:08 UTC, alansemenov approved these changes

2022-08-23 14:17 UTC, rymsha approved these changes

2022-08-23 19:30 UTC, merged