Docs for virtual app config #421
enonic/doc-xp pull request #422
Opened 2022-09-06 08:29 UTC by vbradnitski

2022-09-06 08:57 UTC, closed without merging

2022-09-09 09:36 UTC, alansemenov approved these changes

2022-09-12 12:54 UTC, rymsha requested changes

2022-09-13 07:49 UTC, rymsha requested changes

2022-09-13 07:49 UTC, rymsha commented on docs/deployment/config.adoc
> +virtual.schema.override:: If there is a schema in the virtual application with the same name as in the real one, priority will be given to the scheme from the virtual application. Default: `true`.
```suggestion
virtual.schema.override:: When set to `true`, virtual application schemes will have a priority over schemes in a real application with the same name. When set to `false` virtual application schemes have no affect if real application with the same name exists. Default: `true`.
```

2022-09-13 07:51 UTC, rymsha approved these changes