Virtual applications docs #441
enonic/doc-xp pull request #442
Opened 2022-10-14 11:55 UTC by vbradnitski

2022-10-14 12:58 UTC, rymsha requested changes

2022-10-14 12:58 UTC, rymsha commented on docs/cms/sites.adoc
> +However, sites have an ability to let you add applications to them. Site applications isolated from <<projects#, projects>> applications and can't be inherited.
```suggestion
However, sites have an ability to let you add applications to them. Site applications isolated from <<projects#, projects>> applications. If a site needs an application from its project - add the application to the site.
```

2022-10-17 11:01 UTC, alansemenov commented on docs/apps.adoc
> +For more details, check out the <<apps/virtual-applications#, virtual applications>>.
```suggestion
For more details, check out the <<apps/virtual-applications#, virtual applications documentation>>.
```

2022-10-17 11:02 UTC, alansemenov commented on docs/apps/projects.adoc
> +Below it is an extensive version of a project structure, listing all standard folders and files that can be used
```suggestion
Below is an extensive version of a project structure, listing all standard folders and files that can be used
```

2022-10-17 11:05 UTC, alansemenov commented on docs/apps/virtual-applications.adoc
> +Depends on app config, xp can work with application resources in different modes:
```suggestion
Depending on app config, XP can work with application resources in different modes:
```

2022-10-17 11:06 UTC, alansemenov commented on docs/apps/virtual-applications.adoc
> +    If specified resource is presented in both virtual and bundled app, then virtual will be used.
```suggestion
    If a specified resource is present in both a virtual and a bundled app, then the virtual one will be used.
```

2022-10-17 11:06 UTC, alansemenov commented on docs/apps/virtual-applications.adoc
> +    Resources only from bundled applications are used, virtual apps are disabled and its resources are ignored.
```suggestion
    Only resources from bundled applications are used, virtual apps are disabled and their resources are ignored.
```

2022-10-17 11:07 UTC, alansemenov commented on docs/apps/virtual-applications.adoc
> +    If specified resource is presented in both virtual and bundled app, then virtual will be used.
This is exactly the same as description for "VIRTUAL", and doesn't seem right.

2022-10-17 11:08 UTC, alansemenov commented on docs/apps/virtual-applications.adoc
> +Check the <<../deployment/config#application, documentation>> to find how config the mode.
```suggestion
Check the <<../deployment/config#application, documentation>> to find out how to configure each mode.
```

2022-10-17 11:13 UTC, alansemenov commented on docs/cms/projects.adoc
> +Just like with sites, applications can be added to projects. All functionality and all schemas (content types, schemas, mixins) and descriptors (pages, parts, layouts) from the app will be available
```suggestion
Just like with sites, applications can be added to projects. All functionality and all schemas (content types, schemas, mixins) and descriptors (pages, parts, layouts) from an app will be available within the scope of the project down to a site. 

IMPORTANT: Sites override project applications. If a site should use an application already assigned to its project, you must assign the application directly to the site.
```

2022-10-17 11:16 UTC, alansemenov commented on docs/cms/sites.adoc
> +However, sites have an ability to let you add applications to them. Site applications isolated from <<projects#, projects>> applications. If a site needs an application from its project - add the app
```suggestion
Sites can also have applications assigned to them. Site applications are isolated from <<projects#, project>> applications. If a site should use an application already assigned to its project, you must assign the application directly to the site.
```

2022-10-21 09:11 UTC, alansemenov commented on docs/apps/virtual-applications.adoc
> +Check the <<../deployment/config#application, documentation>> to find out how to configure application behaviour.
```suggestion
VIRTUAL::
Shows that only virtual application is present in the system and support of virtual apps is enabled.
BUNDLED::
Can be one of the next cases:
- Only bundled application is present in the system.
- Both bundled and virtual applications are present, but bundled resources are configured to override virtual.
- Both bundled and virtual applications are present, but virtual app support is disabled via config.
AUGMENTED::
Both bundled and virtual applications are present in the system and virtual resources override bundled.

Check the <<../deployment/config#application, documentation>> to find out how to configure application behaviour.
```

2022-10-21 09:12 UTC, alansemenov approved these changes

2022-10-21 09:20 UTC, rymsha approved these changes

2022-10-21 10:24 UTC, merged