Add docs for content audit log filter #458
enonic/doc-xp pull request #459
Opened 2022-12-23 09:42 UTC by vbradnitski

2023-01-02 12:14 UTC, alansemenov requested changes

2023-01-02 12:14 UTC, alansemenov commented on docs/deployment/config.adoc
> +Rule can be suffixed with `*` - that is a wildcard rule.
```suggestion
A rule prefixed with `!` is a `deny` rule, otherwise it is an `allow` rule.
A rule suffixed with `*` is a wildcard rule.
```

2023-01-02 12:14 UTC, alansemenov commented on docs/deployment/config.adoc
> +Rules applied in order. First matching rule wins. If no matching rule found, event type is denied.
```suggestion
Rules are applied in sequence. A first matching rule wins. If no matching rule found, event type is denied.
```

2023-01-04 14:39 UTC, rymsha requested changes

2023-01-04 14:39 UTC, rymsha commented on docs/deployment/config.adoc
> +auditlog.filter:: Comma separated values `rule(,rule)\*` of allow/deny rules. Default: `*` (allow all).
default is different `!system.content.update,*`

2023-01-07 09:41 UTC, rymsha approved these changes

2023-01-17 10:22 UTC, alansemenov approved these changes

2023-01-17 10:22 UTC, merged