Document siteConfig in lib-project #465
enonic/doc-xp pull request #471
Opened 2023-01-24 16:45 UTC by vbradnitski

2023-01-24 17:03 UTC, alansemenov requested changes

2023-01-24 17:03 UTC, alansemenov commented on docs/cms/projects.adoc
> +Just like with sites, applications can be added to projects and config could be specified for every application. All functionality and all schemas (content types, schemas, mixins) and descriptors (pa
```suggestion
Similar to how applications can be assigned to sites, they (and their configs) can also be assigned (on even a higher level) to content projects. All functionality, schemas (content types, schemas, mixins etc.) and descriptors (pages, parts, layouts) from all assigned applications will be available within the scope of the project down to a site.
```

2023-01-24 18:34 UTC, rymsha approved these changes

2023-01-31 08:29 UTC, alansemenov approved these changes

2023-01-31 08:38 UTC, merged