Document duplicate for Node & Content JS API #474
enonic/doc-xp pull request #475
Opened 2023-01-26 12:47 UTC by anatol-sialitski

2023-01-26 15:06 UTC, rymsha requested changes

2023-01-26 15:06 UTC, rymsha commented on docs/api/lib-content.adoc
> +| Name | Type | Description
There should be <optional> attribute for some

2023-01-31 08:55 UTC, alansemenov approved these changes

2023-01-31 10:10 UTC, rymsha approved these changes

2023-01-31 10:11 UTC, merged